### ISSUE TITLE
Adapter doesnt Start at all 

### ISSUE THREAD

**Issue by Erti1337** [soef/ioBroker.alexa#1]
host.ioBroker-Pi | 2017-12-19 15:59:39.950 | error | instance system.adapter.alexa.0 terminated with code 0 (OK)
-- | -- | -- | --
host.ioBroker-Pi | 2017-12-19 15:59:39.949 | error | Caught by controller[0]:     at safeCallback (/opt/iobroker/node_modules/iobroker.alexa/node_modules/soef/soef.js:188:13)
host.ioBroker-Pi | 2017-12-19 15:59:39.949 | error | Caught by controller[0]:     at doit (/opt/iobroker/node_modules/iobroker.alexa/node_modules/soef/soef.js:249:13)
host.ioBroker-Pi | 2017-12-19 15:59:39.949 | error | Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.alexa/node_modules/soef/soef.js:765:22
host.ioBroker-Pi | 2017-12-19 15:59:39.948 | error | Caught by controller[0]:     at Devices.setStateEx (/opt/iobroker/node_modules/iobroker.alexa/node_modules/soef/soef.js:702:17)
host.ioBroker-Pi | 2017-12-19 15:59:39.947 | error | Caught by controller[0]:     at safeCallback (/opt/iobroker/node_modules/iobroker.alexa/node_modules/soef/soef.js:188:13)
host.ioBroker-Pi | 2017-12-19 15:59:39.946 | error | Caught by controller[0]:     at doit (/opt/iobroker/node_modules/iobroker.alexa/node_modules/soef/soef.js:247:24)
host.ioBroker-Pi | 2017-12-19 15:59:39.945 | error | Caught by controller[0]:     at safeCallback (/opt/iobroker/node_modules/iobroker.alexa/node_modules/soef/soef.js:188:13)
host.ioBroker-Pi | 2017-12-19 15:59:39.943 | error | Caught by controller[0]:     at devices.update (/opt/iobroker/node_modules/iobroker.alexa/alexa.js:315:18)
host.ioBroker-Pi | 2017-12-19 15:59:39.942 | error | Caught by controller[0]:     at AlexaRemote.Alexa.updateStates (/opt/iobroker/node_modules/iobroker.alexa/alexa.js:134:7)
host.ioBroker-Pi | 2017-12-19 15:59:39.940 | error | Caught by controller[0]:     at doIt (/opt/iobroker/node_modules/iobroker.alexa/alexa.js:112:30)
host.ioBroker-Pi | 2017-12-19 15:59:39.939 | error | Caught by controller[0]: TypeError: Cannot read property 'length' of undefined
alexa.0 | 2017-12-19 15:59:39.784 | info | starting. Version 0.0.28 in /opt/iobroker/node_modules/iobroker.alexa, node: v6.12.2
host.ioBroker-Pi | 2017-12-19 15:59:38.089 | info | instance system.adapter.alexa.0 started with pid 2514

And What is the Base Url field for ?

k r
Erti

**Comment by soef** [comment]
Should be fixed in version 0.0.31. Base URL just now should be left empty.

**Comment by Erti1337** [comment]
ty !

**Comment by oliveramann** [comment]
After running some Days with no errors, same Error Messages apear in my Installation,
Version is already  0.0.31

`

host.LXC-Ubuntu | 2018-02-13 21:23:34.051 | info | Restart adapter system.adapter.alexa.0 because enabled
-- | -- | -- | --
host.LXC-Ubuntu | 2018-02-13 21:23:34.051 | error | instance system.adapter.alexa.0 terminated with code 0 (OK)
Caught | 2018-02-13 21:23:34.051 | error | by controller[0]: at safeCallback (/opt/iobroker/node_modules/iobroker.alexa/node_modules/soef/soef.js:188:13)
Caught | 2018-02-13 21:23:34.051 | error | by controller[0]: at doit (/opt/iobroker/node_modules/iobroker.alexa/node_modules/soef/soef.js:249:13)
Caught | 2018-02-13 21:23:34.051 | error | by controller[0]: at /opt/iobroker/node_modules/iobroker.alexa/node_modules/soef/soef.js:765:22
Caught | 2018-02-13 21:23:34.051 | error | by controller[0]: at Devices.setStateEx (/opt/iobroker/node_modules/iobroker.alexa/node_modules/soef/soef.js:702:17)
Caught | 2018-02-13 21:23:34.050 | error | by controller[0]: at safeCallback (/opt/iobroker/node_modules/iobroker.alexa/node_modules/soef/soef.js:188:13)
Caught | 2018-02-13 21:23:34.050 | error | by controller[0]: at doit (/opt/iobroker/node_modules/iobroker.alexa/node_modules/soef/soef.js:247:24)
Caught | 2018-02-13 21:23:34.050 | error | by controller[0]: at safeCallback (/opt/iobroker/node_modules/iobroker.alexa/node_modules/soef/soef.js:188:13)
Caught | 2018-02-13 21:23:34.050 | error | by controller[0]: at devices.update (/opt/iobroker/node_modules/iobroker.alexa/alexa.js:317:18)
Caught | 2018-02-13 21:23:34.050 | error | by controller[0]: at AlexaRemote.Alexa.updateStates (/opt/iobroker/node_modules/iobroker.alexa/alexa.js:134:7)
Caught | 2018-02-13 21:23:34.050 | error | by controller[0]: at doIt (/opt/iobroker/node_modules/iobroker.alexa/alexa.js:112:30)
Caught | 2018-02-13 21:23:34.049 | error | by controller[0]: TypeError: Cannot read property 'length' of undefined
alexa.0 | 2018-02-13 21:23:34.029 | info | terminating
alexa.0 | 2018-02-13 21:23:33.996 | error | at safeCallback (/opt/iobroker/node_modules/iobroker.alexa/node_modules/soef/soef.js:188:13)
alexa.0 | 2018-02-13 21:23:33.996 | error | at doit (/opt/iobroker/node_modules/iobroker.alexa/node_modules/soef/soef.js:249:13)
alexa.0 | 2018-02-13 21:23:33.996 | error | at /opt/iobroker/node_modules/iobroker.alexa/node_modules/soef/soef.js:765:22
alexa.0 | 2018-02-13 21:23:33.996 | error | at Devices.setStateEx (/opt/iobroker/node_modules/iobroker.alexa/node_modules/soef/soef.js:702:17)
alexa.0 | 2018-02-13 21:23:33.996 | error | at safeCallback (/opt/iobroker/node_modules/iobroker.alexa/node_modules/soef/soef.js:188:13)
alexa.0 | 2018-02-13 21:23:33.996 | error | at doit (/opt/iobroker/node_modules/iobroker.alexa/node_modules/soef/soef.js:247:24)
alexa.0 | 2018-02-13 21:23:33.996 | error | at safeCallback (/opt/iobroker/node_modules/iobroker.alexa/node_modules/soef/soef.js:188:13)
alexa.0 | 2018-02-13 21:23:33.996 | error | at devices.update (/opt/iobroker/node_modules/iobroker.alexa/alexa.js:317:18)
alexa.0 | 2018-02-13 21:23:33.996 | error | at AlexaRemote.Alexa.updateStates (/opt/iobroker/node_modules/iobroker.alexa/alexa.js:134:7)
alexa.0 | 2018-02-13 21:23:33.996 | error | at doIt (/opt/iobroker/node_modules/iobroker.alexa/alexa.js:112:30)
alexa.0 | 2018-02-13 21:23:33.996 | error | TypeError: Cannot read property 'length' of undefined
alexa.0 | 2018-02-13 21:23:33.994 | error | uncaught exception: Cannot read property 'length' of undefined
alexa.0 | 2018-02-13 21:23:32.342 | info | starting. Version 0.0.31 in /opt/iobroker/node_modules/iobroker.alexa, node: v6.12.3
host.LXC-Ubuntu | 2018-02-13 21:23:31.193 | info | instance system.adapter.alexa.0 started with pid 23623
host.LXC-Ubuntu | 2018-02-13 21:23:01.184 | info | Restart adapter system.adapter.alexa.0 because enabled

`
Thanks
Oli

**Comment by h3adbang3r** [comment]
host.ioBroker-Pi | 2018-03-10 15:19:59.438 | error | instance system.adapter.alexa.0 terminated with code 0 (OK)
-- | -- | -- | --
Caught | 2018-03-10 15:19:59.437 | error | by controller[0]:     at safeCallback (/opt/iobroker/node_modules/iobroker.alexa/node_modules/soef/soef.js:188:13)
Caught | 2018-03-10 15:19:59.437 | error | by controller[0]:     at doit (/opt/iobroker/node_modules/iobroker.alexa/node_modules/soef/soef.js:249:13)
Caught | 2018-03-10 15:19:59.436 | error | by controller[0]:     at /opt/iobroker/node_modules/iobroker.alexa/node_modules/soef/soef.js:765:22
Caught | 2018-03-10 15:19:59.435 | error | by controller[0]:     at Devices.setStateEx (/opt/iobroker/node_modules/iobroker.alexa/node_modules/soef/soef.js:702:17)
Caught | 2018-03-10 15:19:59.432 | error | by controller[0]:     at safeCallback (/opt/iobroker/node_modules/iobroker.alexa/node_modules/soef/soef.js:188:13)
Caught | 2018-03-10 15:19:59.432 | error | by controller[0]:     at doit (/opt/iobroker/node_modules/iobroker.alexa/node_modules/soef/soef.js:247:24)
Caught | 2018-03-10 15:19:59.431 | error | by controller[0]:     at safeCallback (/opt/iobroker/node_modules/iobroker.alexa/node_modules/soef/soef.js:188:13)
Caught | 2018-03-10 15:19:59.431 | error | by controller[0]:     at devices.update (/opt/iobroker/node_modules/iobroker.alexa/alexa.js:317:18)
Caught | 2018-03-10 15:19:59.430 | error | by controller[0]:     at AlexaRemote.Alexa.updateStates (/opt/iobroker/node_modules/iobroker.alexa/alexa.js:134:7)
Caught | 2018-03-10 15:19:59.430 | error | by controller[0]:     at doIt (/opt/iobroker/node_modules/iobroker.alexa/alexa.js:112:30)
Caught | 2018-03-10 15:19:59.429 | error | by controller[0]: TypeError: Cannot read property 'length' of undefined

Version 0..0.33 :(

**Comment by soef** [comment]
Hallo, can you please try version 0.0.34 or higher?

**Comment by h3adbang3r** [comment]
hallo,
nice, 0.0.35 works fine ;)
